export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="overflow-x-hidden	" lang="en">
      <body>
        <header style={{
          backgroundColor: "coral",
          height: 40
         }}><h1>Ertuzz Networks</h1></header>
        {children}
         <footer>Kontakt: <a href="mailto:ertuzzpvp@gmail.com">Schicke dem Server eine E-Mail</a></footer>
      </body>
    </html>
  )
}
